name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "afrcloudnet1.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloudnet1.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloudnet1.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloudnet1.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.afrcloudnet1.dpdns.org", custom_domain = true },
  { pattern = "zoomgov.com.afrcloudnet1.dpdns.org", custom_domain = true }
  ]

[[kv_namespaces]]
binding = "SIREN"
id = "f03343e35e3d4883be04ed0884364eb5"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/rohendimtq22/SIREN/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/rohendimtq22/SIREN/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/rohendimtq22/SIREN/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/rohendimtq22/SIREN/refs/heads/master/web/converter.html"
